version: '2'

services:
  base:
    image: golang:alpine3.11
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - ARTEFACT_BUCKET=awsweeper-bucket
      - APP_NAME=awsweeper
      - LAMBDA_PACKAGE=tmp/awsweeper.zip
      - DEPLOYMENT_PACKAGE_PATH=lambda/awsweeper.zip
      - LAMBDA_FUNCTION_NAME=awsweeperLoader
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh

  awsweeper:
    image: 494526681395.dkr.ecr.ap-northeast-2.amazonaws.com/tw-toc/awsweeper:v0.9.0
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
    volumes:
      - ./log/:/app/log/
    working_dir: /app
