version: '2'

services:
  base:
    image: golang:alpine3.11
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - ARTEFACT_BUCKET=awsweeper-bucket
      - APP_NAME=awsweeper
      - PACKAGE_NAME=awsweeper.zip
      - DEPLOYMENT_PACKAGE_PATH=lambda/awsweeper.zip
      - LAMBDA_FUNCTION_NAME=awsweeperLoader
    volumes:
      - .:/app
    working_dir: /app
    command: bash
