AWSTemplateFormatVersion: 2010-09-09
Description: awsweeper is simply to cleanup aws resources.
Parameters:
  AwsweeperS3Bucket:
    Type: String
    Description: The S3 bucket in which the lambda function code is stored.
  LambdaFunctionS3Key:
    Type: String
    AllowedPattern: .*\.zip
    Description: The S3 object for the lambda function code package.
  LambdaFunctionName:
    Type: String
    Description: express lambda function name
  LambdaExecutionSchedule:
    Type: String
    Description: The schedule of the lambda function execution
  VpcId:
    Type: String
    Description: Lambda VPC
  SubnetIds:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: lambda subnets
  LambdaMemorySize:
    Type: Number
    Description: Lambda memory size
  LambdaRuntime:
    Type: String
    Description: Lambda runtime
  LambdaTimeout:
    Type: Number
    Description: Lambda timeout
  Owner:
    Type: String
    Description: Service owner
  LambdaSourceAccount:
    Type: String
    Description: Source account
  LambdaExecutionRole:
    Type: String
    Description: Lambda IAM role
  S3BucketRegion:
      Type: String
      Description: S3 Bucket Region
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    DependsOn: CloudwatchLogs
    Properties:
      Code:
        S3Bucket: !Sub ${AwsweeperS3Bucket}-${S3BucketRegion}
        S3Key: !Ref LambdaFunctionS3Key
      FunctionName: !Ref LambdaFunctionName
      Handler: src/awsweeper.lambda_handler
      MemorySize: !Ref LambdaMemorySize
      Role: !Ref LambdaExecutionRole
      Runtime: !Ref LambdaRuntime
      Timeout: !Ref LambdaTimeout
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Owner
          Value: !Ref Owner
  ScheduledEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Scheduled Lambda Invocation Rule
      ScheduleExpression: !Ref LambdaExecutionSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt 
            - LambdaFunction
            - Arn
          Id: LambdaFunctionTarget
  LambdaPermissionForScheduledEvents:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - LambdaFunction
        - Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 
        - ScheduledEventRule
        - Arn
  LambdaPermisionForS3Bucket:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - LambdaFunction
        - Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref LambdaSourceAccount
      SourceArn: !Sub arn:aws:s3:::${AwsweeperS3Bucket}-${S3BucketRegion}
  LambdaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for lambda
      VpcId: !Ref VpcId
      Tags:
        - Key: Owner
          Value: !Ref Owner
  CloudwatchLogs:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LambdaFunctionName}'
      RetentionInDays: '7'
