#!/bin/bash -eu

cd $(dirname $0)/..

source ./auto/set-env-vars
source ./src/env

[ ! -d ./tmp/ ] && mkdir ./tmp/

eval "cat <<EOF
$(cat ./aws/instance/${APP_NAME}-tags.yml)
EOF
" > ./tmp/${APP_NAME}-tags.yml

[ -f ${ARTIFACT} ] && export AWSWEEPER_IMAGE=$(cat ${ARTIFACT})

eval "cat <<EOF
$(cat ./aws/instance/${APP_NAME}-params.yml)
EOF
" > ./tmp/${APP_NAME}-params.yml

display_status "Deploy ${APP_NAME}-instance in ${AWS_DEFAULT_REGION}"

auto/stackup "${APP_NAME}-instance" up \
  --region "${AWS_DEFAULT_REGION}" \
  --template "./aws/instance/${APP_NAME}.yml" \
  --parameters "./tmp/${APP_NAME}-params.yml" \
  --tags "./tmp/${APP_NAME}-tags.yml" \

auto/cleanup
