#!/bin/bash -eu

cd $(dirname $0)/..

ENV=${1:-"Singapore"}
source ./auto/set-env-vars
source ./aws/lambda/${ENV}/awsweeper-env-vars

auto/package-publish ${VERSION} ${AWS_REGION}

display_status "Deploy ${APP_NAME}-lambda in ${AWS_REGION}"

auto/stackup "${APP_NAME}-lambda" up \
  --region "${AWS_REGION}" \
  --template "./lambda/${ENV}/${APP_NAME}.yml" \
  --parameters "./lambda/${ENV}/${APP_NAME}-params.yml" \
  --tags "./lambda/${ENV}/${APP_NAME}-tags.yml" \
  --override "LambdaFunctionS3Key=lambda/${APP_NAME}-${VERSION}.zip"
