#!/bin/bash -eu

cd $(dirname $0)/..
source ./auto/set-env-vars

./auto/package

./auto/deploy-lambda-role

./auto/deploy-lambda-in-Seoul

./auto/deploy-lambda-in-Singapore

./auto/deploy-lambda-in-Sydney

./auto/deploy-lambda-in-Tokyo

./auto/cleanup
