#!/bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-vars

display_status "Packaging"

[ ! -d ./tmp/ ] && mkdir ./tmp/

docker-compose run \
	--rm base \
	sh -c "sh ./install.sh ${AWSWEEPER_VERSION} \
	&& apk add --no-cache zip \
	&& zip -q -r ${LAMBDA_PACKAGE} src bin config"
