#!/bin/bash -eu

cd $(dirname $0)/..
source ./auto/set-env-vars

display_status "Uploading artefacts to artefacts S3 bucket"
aws s3 cp "${LAMBDA_PACKAGE}" "s3://${ARTEFACT_BUCKET}-$2/lambda/${APP_NAME}-$1.zip"
