#! /bin/bash -eu
#
# Publish Docker image

cd $(dirname $0)/..
source ./auto/set-env-vars

login_ecr

[ ! -d ./tmp/ ] && mkdir ./tmp/

# Build the image
./auto/build-docker-image

# Release to registry
_AWSWEEPER_IMAGE=${AWSWEEPER_IMAGE}:${AWSWEEPER_IMAGE_VERSION}
docker tag ${AWSWEEPER_IMAGE} ${_AWSWEEPER_IMAGE}
docker push ${AWSWEEPER_IMAGE}
docker push ${_AWSWEEPER_IMAGE}
display_status "Pushed docker image ${AWSWEEPER_IMAGE} with tags ${_AWSWEEPER_IMAGE}, latest"
echo ${_AWSWEEPER_IMAGE} > ./tmp/artifacts.conf
