#!/bin/bash -eu

APP_NAME="awsweeper"
ARTEFACT_BUCKET="${APP_NAME}-artefact-bucket"
ARTEFACT_BUCKET_ROLE=""
LAMBDA_PACKAGE="./tmp/${APP_NAME}.zip"
AWS_DEFAULT_REGION="ap-southeast-1"
AWSWEEPER_VERSION="v0.9.0"

display_status() {
  echo ">>> $1 <<<" 1>&2
}
