#!/bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-vars

IMAGE="${STACKUP_IMAGE}:${STACKUP_VERSION}"

exec docker run -v ${PWD}:/cwd \
  --workdir /cwd \
  --env AWS_ACCESS_KEY_ID \
  --env AWS_SECRET_ACCESS_KEY \
  --env AWS_SESSION_TOKEN \
  "${IMAGE}" "$@"
